before_build:
 - nuget restore
build_script:
 - msbuild /verbosity:quiet "codecov-on-appveyor.sln"
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"Tests\bin\Debug\tests.dll -noshadow" -output:"coverage.xml" -filter:"+[Tests*]*"
after_test:
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "CanoePoloLeagueOrganiser_coverage.xml"
